### ISSUE TITLE
RuboCop 設定を Gem にする

### ISSUE THREAD

**Issue by epaew** [timedia/styleguide#14]
### 言語（フレームワーク）
- Ruby

### 現状どうなっている
- RuboCopの共通設定を使うときは `.rubocop.yml` の `inherit_from` に、raw.githubusercontent.com の URL を指定してもらうことを想定している
  - Pros:
    - styleguide の master の RuboCop 設定が更新されたときに、PJ 側で特に対応しなくても最新の RuboCop 設定が適用される
  - Cons:
    - RuboCop のバージョンアップで Cop が追加され、styleguide 側でそれに対応した場合、古いバージョンの RuboCop では新しい Cop を解釈できず、RuboCop の実行に失敗する
    - Project root に、`.rubocop-https---xxx` といったキャッシュファイルが勝手に作られてしまう
      - gitignore してもらえばいいだけだけど、若干気持ち悪い

### どうなってほしい
- RuboCop の共通設定が、Gem として配信される
  - 各 PJ では、Gemfile 経由で preset をインストールし、`.rubocop.yml` 内の `inherit_gem` で指定してもらうことになる
    - Pros:
      - RuboCop 設定の意図しない変更を防ぐことができる
    - Cons:
      - Gemfile を更新してくれない PJ は絶対出てくる

- TODO:
  - Gem の versioning
    - 日付とかでいいのでは
  - 配信元を rubygems.org or GitHub Packages どっちにするか
    - timedia の rubygems アカウントって、多分今ないよね？

**Comment by epaew** [comment]
[IMO]

あと、個人的に TypeScript 用の ESLint 設定もいずれ styleguide リポジトリに入れたいと思ってて、
けど ESLint の config presets は node_modules/ からしか読めないので、そっちは対応しようと思ったら npm package 化が必須なのです。。

なので package で配信するように合わせたいってのも多少あります

**Comment by yujideveloper** [comment]
パッケージとして配信するかは置いておいてGem化するのは必要そうです。
Gitリポジトリ指定でもアップデートしない限りはコミットハッシュ固定されるのでstyleguideの更新で意図せずRuboCopの実行が壊れるのは防げそうです。

**Comment by epaew** [comment]
https://bundler.io/guides/git.html

> If the gem is located within a subdirectory of a git repository, you can use the :glob option to specify the location of its .gemspec
> ```
> gem 'cf-copilot', git: 'https://github.com/cloudfoundry/copilot', glob: 'sdk/ruby/*.gemspec'
> ```

`ruby/rubocop-timedia.gemspec` を置いて
```ruby
# Gemfile
gem 'rubocop-timedia', git: 'https://github.com/timedia/styleguide', glob: 'ruby/rubocop-timedia.gemspec'
```
とか書けばよさそう
