### ISSUE TITLE
RuboCop docs へのリンクが切れている

### ISSUE THREAD

**Issue by epaew** [timedia/styleguide#45]
### 言語（フレームワーク）
Ruby

### 現状どうなっている
Yamlのコメントに記載しているRuboCop docs へのリンクが切れている。RuboCop 1.xがリリースされた影響？
e.g. https://github.com/timedia/styleguide/pull/15#discussion_r514637232

### どうなってほしい
RuboCop docs への有効なリンクが記載されている

#### Note
* master: https://docs.rubocop.org/rubocop/cops_metrics.html#metricsparameterlists
* 1.1: https://docs.rubocop.org/rubocop/1.1/cops_metrics.html#metricsparameterlists
* 1.0: https://docs.rubocop.org/rubocop/1.0/cops_metrics.html#metricsparameterlists

のように「バージョンごと+master」の docs がある模様。master へのリンクでいいかな。

**Comment by yohei-yamazaki** [comment]
https://github.com/timedia/styleguide/pull/56 がmergeされてRuboCop docsのmasterへのリンクに飛ぶようになりましたのでcloseします。
