### ISSUE TITLE
rubocop.yml を分割する

### ISSUE THREAD

**Issue by epaew** [timedia/styleguide#6]
https://github.com/timedia/styleguide/pull/2#issuecomment-630685340

> このPRに書くのが良いか微妙なんだけど、RuboCopの設定ファイルはRuboCopのGem毎にファイルを分けてしまうのが良いと思います。
> どれを使うかは案件で選んでしまってよいと思います。
> ↓のように配置するイメージです。
> 
> * rubocop/default.yml
>   
>   * RuboCop本体用の設定
> * rubocop/performance.yml
>   
>   * rubocop-performance用の設定
> * rubocop/rails.yml
>   
>   * rubocop-rails用の設定
> * rubocop/rspec.yml
>   
>   * rubocop-rspec用の設定
> 
> これをする理由は、僕たちの案件ではRailsだけではなくてHanamiも使っていて、その時も設定ファイルを使いたいとか、内部用のGemだからRuboCopの本体だけでいいとかそういう選択をしたいです。

**Comment by epaew** [comment]
@yujideveloper 

私も、
* /ruby: Pure Ruby 用
* /ruby-rails: RoR 用

は欲しいなあと思ってました。それぞれ単独で使う想定ではありましたが。
（あと /typescript とかも追加できたらいいなとも思ってました）

少し変えて、
* /ruby
* /ruby-performance # `/ruby` と一緒に使う (optional)
* /ruby-rails # 同上
* /ruby-rspec # 同上

あたりにしようと思いますがどうでしょうか

**Comment by epaew** [comment]
ただ Performance は /ruby に混ぜちゃってもいい気もする

**Comment by epaew** [comment]
> * /ruby: Ruby 用の RuboCop 基本設定
> * /ruby-performance: `/ruby` と一緒に使う (optional)
> * /ruby-rails: 同上
> * /ruby-rspec: 同上
> 
> あたりにしようと思いますがどうでしょうか

（半分個人的な趣味）
あんまり root から分岐するのも微妙かなと思ったので、やっぱり

```
/
+-/ruby <- ruby or rubocop で迷い中、どっちでもいいか。
  +-/base
  +-/performance <- base に混ぜるか検討
  +-/rails
  +-/rspec
```

のほうが好きかも

**Comment by yujideveloper** [comment]
RuboCopの設定ファイルは `.rubocop` で始まるかどうかとかでExcludeとかの検索のベースパスが変わるとかがあった気がするのでそのあたりは要注意ですかね。

> ただ Performance は /ruby に混ぜちゃってもいい気もする

これについては強い思いはないです（僕は必ず入れたい派なので

`/ruby/rubocop/` にRuboCop系をファイル分けておいていくのがいいかなという趣味。

**Comment by epaew** [comment]
> `/ruby/rubocop/` にRuboCop系をファイル分けておいていくのがいいかなという趣味。

作りながら「やっぱこうだな…」って変えた方針と一致してたので、とりあえず分割の方針はこれで行きたいと思います


> RuboCopの設定ファイルは `.rubocop` で始まるかどうかとかでExcludeとかの検索のベースパスが変わるとかがあった気がするのでそのあたりは要注意ですかね。
> 
> ref. https://github.com/rubocop-hq/rubocop/blob/3651d6b42181b37fedd293b548cff7a4b37f5add/manual/configuration.md#path-relativity

ありがとうございます。適当な Rails project の rubocop.yml いじって確認してみますね。


> > ただ Performance は /ruby に混ぜちゃってもいい気もする
> 
> これについては強い思いはないです（僕は必ず入れたい派なので
> 
👍

**Comment by epaew** [comment]
> > RuboCopの設定ファイルは `.rubocop` で始まるかどうかとかでExcludeとかの検索のベースパスが変わるとかがあった気がするのでそのあたりは要注意ですかね。
> > ref. https://github.com/rubocop-hq/rubocop/blob/3651d6b42181b37fedd293b548cff7a4b37f5add/manual/configuration.md#path-relativity
> 
> ありがとうございます。適当な Rails project の rubocop.yml いじって確認してみますね。

inherit_from に url を指定したときの挙動としては、
* ローカルに `.rubocop-https---raw-githubusercontent-...base-yml` を保存して、そこから読み込む
    * ドキュメントによると、このキャッシュは最大24時間有効

なので、Exclude の検索 Path の挙動は特に問題なさそう
